### ISSUE TITLE
Notes encoding

### ISSUE THREAD

**Issue by tomaspaukste** [Ogefest/Notepack#20]
Hi, firstly - great app :) But found one place to improve - when saving files on Windows it uses Windows-XXXX encoding and Linux line endings (LF). It would be great to change it all to simple utf-8 encoding or to have ability choose it (in app settings or in some config file). Because it's almost impossible to open created note files (when they have non English letters inside) with other simple text editors (only in npp with choosing settings). Thanks!

**Comment by Ogefest** [comment]
Hello my first issue reporter :)

I only want to confirm, you mean file content encoding? I'm linux user day by day and I was pretty sure that utf8 is common standard for encoding. Add default encoding in workspace settings seems be quite easy to do, if it's improve Notepack it make sense for me.

**Comment by tomaspaukste** [comment]
Hi, yes I mean file encoding. It seems that app gets default encoding from Windows locale settings. I'm using Lithuanian settings, so files are saved with character set Windows-1257.

But here you need to be careful, maybe add this utf-8 setting as optional, because if you will set it as default, current users after app update will not see their non-English symbols correctly.

Also another remark - Windows/Linux/Macintosh each system has different text line ending symbol (Windows - CR LF, Linux LF, Macintosh - CR), so it would be reasonable to follow it. Now current file in Windows has Linux line endings LF.

**Comment by Ogefest** [comment]
It take me more time than I thought before but I needed to prepare windows dev environment which was quite hard for long time linux user.

Anyway, I added extra checkbox in workspace configuration. If default encoding in system is UTF-8 like Ubuntu this checkbox is hidden but when system encoding is for example windows-1257 (I tested with windows-1250 - Poland here) then extra checkbox is available, if you set this on then all content saved is converting to UTF-8. Tested in many ways seems works as expected. You can check by yourself with [0.9.13 release](https://github.com/Ogefest/Notepack/releases/tag/v0.9.13) 

I have to think about end lines, for sure this could be an issue in some cases but right now I'm try to avoid overload settings in workspace configuration.

Thank you involve, if you have some ideas feel free to write them. I have plans to make Notepack best knowledge app for desktops

**Comment by tomaspaukste** [comment]
Thanks! Now it works well :)
