### ISSUE TITLE
Loss of note if saved with "/" in filename

### ISSUE THREAD

**Issue by Alex9001** [Ogefest/Notepack#26]
This probably applies to other disallowed symbols.

When using Filesystem on Win32, saving a note.txt with a / in the name (Ex: Misc/Etc.txt) provides a non-descriptive error dialogue that simply states "Dialogue: //Filepath". 

At that point the note becomes unsavable as there is no way to rename the note after saving it the first time.

At that point closing the note pops up a choice to save or discard the note, clicking save repeats error dialogue and does not save note.

**Comment by Ogefest** [comment]
Thank you @Alex9001 for your contribution. I've checked your problem and you are right. Main reason is described https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names which make sense why Notepack can't save notes under windows.

Good news is that I fixed this issue and fresh release are ready to download from Notepack release page version [v0.9.16](https://github.com/Ogefest/Notepack/releases/tag/v0.9.16) show proper message when you try to use those chars.

If you find any other problems or have ideas which can improve Notepack feel free to create new issues, on current development stage most of ideas could be easy to develop.
