### ISSUE TITLE
Freeze/crash and rollback after importing PDF

### ISSUE THREAD

**Issue by Alex9001** [Ogefest/Notepack#28]
Using LibreOffice Writer 7.1.1.2 create a document with any text.

Go to file>Export As>PDF>default options>Export>Save as "Untitled 1.pdf"

In Notepack create new Filesystem workspace called Test at C:\Users\user\Desktop\test

- Enable encryption
- Save using UTF-8
- Password: 12345

Import file>"Untitled 1.pdf"

It doesn't work.

Try to create new note, enter anything save as any filename 
Error: Invalid Filename. 
Note won't save.

Program is now unusable.

Close Notepack.exe

Open notepack.exe

It has now rolled back to previous state.

Open the imported PDF

Does not work

Try to rename PDF: Invalid note name

Program is now unusable.

**Comment by Ogefest** [comment]
@Alex9001 could you check if the same problem occur when you have unchecked "UTF-8 Encoding" in workspace configuration? I guess problem appear when I added this option and internally Notepack try to convert Windows encoding to UTF-8 which make sense with text files but not with pdf. I'll also check it but probably tomorrow.

**Comment by Alex9001** [comment]
I just verified: there is no issue if UTF-8 is unchecked.

**Comment by Ogefest** [comment]
Thank you, so I need to add checking what kind of note is save as UTF-8, probably with images you will get the same problem. Should be easy to fix, will do it tomorrow.

**Comment by Ogefest** [comment]
Fresh fixed version is ready to download from [github release page](https://github.com/Ogefest/Notepack/releases/tag/v0.9.17) This bug also appear for other non text formats. I've created list extensions where convert between windows encoding and UTF-8 is possible, other formats stays as is.
