### ISSUE TITLE
Cannot scroll all the way down in editor

### ISSUE THREAD

**Issue by zdalekacelny** [Ogefest/Notepack#35]
In most notes that are longer than 50 lines or so it's impossible to scroll all the way down in the edit window, even though the cursor moves down and becomes invisible. It's always possible to scroll all the way down in the preview window.

I've reinstalled the app, but that didn't help. Needless to say, this bug makes this otherwise great app essentially unusable.

I'm using the latest version of Notepack on Ubuntu 21.10.

**Comment by Ogefest** [comment]
Thank you for your contribution. Unfortunately bug exists somewhere in JavaFX and was related with line spacing in text area. When line spacing was changed then scrollbar still had previous calculation and there were not way to scroll to the end of a file.

Right now it's fixed and when you download current version (0.9.22) of Notepack then everything should be fine.
